const EditorTailwindTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'relative m-0 mb-[8px]',
  quote:
    'm-0 ml-[20px] text-[15px] text-foreground border-l-4 border-solid border-gray-300 pl-[16px]',
  heading: {
    h1: 'text-[2.441rem] text-foreground font-normal m-0 mb-3 p-0',
    h2: 'text-[1.953rem] text-foreground font-normal m-0 mb-3 p-0',
    h3: 'text-[1.563rem] text-foreground font-normal m-0 mb-3 p-0',
    h4: 'text-[1.25rem] text-foreground font-normal m-0 mb-3 p-0',
    h5: 'text-[1rem] text-foreground font-normal m-0 mb-3 p-0',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'p-0 m-0 ml-[16px] list-decimal',
    ul: 'p-0 m-0 ml-[16px] list-disc',
    listitem: 'my-2 mx-8',
  },
  image: 'editor-image',
  link: 'text-blue-600 no-underline',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-gray-200 py-0.5 px-1 font-mono text-sm',
  },
  code: 'bg-gray-200 font-mono py-2 px-2 pl-13 leading-relaxed text-sm mx-0 my-2 overflow-x-auto relative',
  codeHighlight: {
    atrule: 'editor-tokenAttr',
    attr: 'editor-tokenAttr',
    boolean: 'editor-tokenProperty',
    builtin: 'editor-tokenSelector',
    cdata: 'editor-tokenComment',
    char: 'editor-tokenSelector',
    class: 'editor-tokenFunction',
    'class-name': 'editor-tokenFunction',
    comment: 'editor-tokenComment',
    constant: 'editor-tokenProperty',
    deleted: 'editor-tokenProperty',
    doctype: 'editor-tokenComment',
    entity: 'editor-tokenOperator',
    function: 'editor-tokenFunction',
    important: 'editor-tokenVariable',
    inserted: 'editor-tokenSelector',
    keyword: 'editor-tokenAttr',
    namespace: 'editor-tokenVariable',
    number: 'editor-tokenProperty',
    operator: 'editor-tokenOperator',
    prolog: 'editor-tokenComment',
    property: 'editor-tokenProperty',
    punctuation: 'editor-tokenPunctuation',
    regex: 'editor-tokenVariable',
    selector: 'editor-tokenSelector',
    string: 'editor-tokenSelector',
    symbol: 'editor-tokenProperty',
    tag: 'editor-tokenProperty',
    url: 'editor-tokenOperator',
    variable: 'editor-tokenVariable',
  },
};

export default EditorTailwindTheme;
