#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Testing and building your project before committing'

# Check ESLint Standards
npm run lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo 'OK, OK...You're The Man...So Far...Now I'm Going To Run Some Tests! 😈😈😈'


# Check Jest Standards
npm run jest ||
(
        echo '❌❌ Jest Told Your Code As A Joke..And Everyone DIEEED Laughing 💀💀😂😂..Fix Errors In Your Code.'
        false;
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# # Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

